### ISSUE TITLE
PipelineTest class testVerifySectionsHaveTooltips to POM

### ISSUE THREAD

**Issue by HelenMyronyuk** [RedRoverSchool/JenkinsQA_2024_spring#1625] opened 2024-06-08 13:20 UTC
PipelineTest class testVerifySectionsHaveTooltips to POM

**Comment by OxanaSum** [comment] 2024-06-15 16:04
Method removed as a duplicate of method testVerifyConfigureSectionsHaveTooltips.

**Closed** 2024-06-15 16:04 UTC
Labels: RF
